//go:build !test_sha256

package git

import (
	"context"
	stdlog "log"
)

var (
	testrepoMarks = map[int64]Oid{
		// Commits, generated by `git rev-list --all | tac`
		1:  MustIDFromString("755fd577edcfd9209d0ac072eed3b022cbe4d39b"),
		2:  MustIDFromString("32c273781bab599b955ce7c59d92c39bedf35db0"),
		3:  MustIDFromString("dc64fe4ab8618a5be491a9fca46f1585585ea44e"),
		4:  MustIDFromString("9cdb160ee4118035bf73c744e3bf72a1ba16484a"),
		5:  MustIDFromString("f5ed01959cffa4758ca0a49bf4c34b138d7eab0a"),
		6:  MustIDFromString("333fd9bc94084c3e07e092e2bc9c22bab4476439"),
		7:  MustIDFromString("2956e1d20897bf6ed509f6429d7f64bc4823fe33"),
		8:  MustIDFromString("369adba006a1bbf25e957a8622d2b919c994d035"),
		9:  MustIDFromString("818f033c4ae7f26b2b29e904942fa79a5ccaadd0"),
		10: MustIDFromString("cb2d322bee073327e058143329d200024bd6b4c6"),
		11: MustIDFromString("57d0bf61e57cdacb309ebd1075257c6bd7e1da81"),
		12: MustIDFromString("2a52e96389d02209b451ae1ddf45d645b42d744c"),
		13: MustIDFromString("8d2636da55da593c421e1cb09eea502a05556a69"),
		14: MustIDFromString("e83ece763cc9d036715c30c8cb0da93b9d480d86"),
		15: MustIDFromString("bf7a9a5ee025edee0e610bd7ba23c0704b53c6db"),
		16: MustIDFromString("d2280d000c84f1e595e4dec435ae6c1e6c245367"),
		17: MustIDFromString("c59479302142d79e46f84d11438a41b39ba51a1f"),
		18: MustIDFromString("78f4771957ffcd015caf609a1721f0fb8ba18cb6"),
		19: MustIDFromString("8d80474ffc3747e3375651cc2a0032c8599befd3"),
		20: MustIDFromString("a13dba1e469944772490909daa58c53ac8fa4b0d"),
		21: MustIDFromString("7c5ee6478d137417ae602140c615e33aed91887c"),
		22: MustIDFromString("435ffceb7ba576c937e922766e37d4f7abdcc122"),
		23: MustIDFromString("9805760644754c38d10a9f1522a54a4bdc00fa8a"),
		24: MustIDFromString("45a30ea9afa413e226ca8614179c011d545ca883"),
		25: MustIDFromString("ebbbf773431ba07510251bb03f9525c7bab2b13a"),
		26: MustIDFromString("ef7bebf8bdb1919d947afe46ab4b2fb4278039b3"),
		27: MustIDFromString("978fb7f6388b49b532fbef8b856681cfa6fcaa0a"),
		28: MustIDFromString("4eaa8d4b05e731e950e2eaf9e8b92f522303ab41"),
		29: MustIDFromString("4e59b72440188e7c2578299fc28ea425fbe9aece"),
		30: MustIDFromString("0eedd79eba4394bbef888c804e899731644367fe"),
		31: MustIDFromString("d58e3ef9f123eea6857161c79275ee22b228f659"),
		32: MustIDFromString("cfc3b2993f74726356887a5ec093de50486dc617"),

		34: MustIDFromString("021a721a61a1de65865542c405796d1eb985f784"), // blob HEAD:.DS_Store
		35: MustIDFromString("412eeda78dc9de1186c2e0e1526764af82ab3431"), // blob HEAD:.gitattributes
		36: MustIDFromString("7c820833a9ad5fbfc96efd533d55f5edc65dc977"), // blob HEAD:.gitignore
		37: MustIDFromString("6abde17f49a6d43df40366e57d8964fee0dfda11"), // blob HEAD:.gitmodules
		38: MustIDFromString("17eccd68b7cafa718d53c8b4db666194646e2bd9"), // blob HEAD:.travis.yml
		39: MustIDFromString("adfd6da3c0a3fb038393144becbf37f14f780087"), // blob HEAD:README.txt
		40: MustIDFromString("6058be211566308428ca6dcab3f08cf270cd9568"), // blob HEAD:build.gradle
		41: MustIDFromString("fcf7087e732bfe3c25328248a9bf8c3ccd85bed4"), // tree HEAD:gogs
		42: MustIDFromString("a41a5a6cfd2d5ec3c0c1101e7cc05c9dedc3e11d"), // tree HEAD:img
		43: MustIDFromString("99975710477a65b89233b2d12bf60f7c0ffc1f5c"), // blob HEAD:pom.xml
		44: MustIDFromString("aaa0af6b82db99c660b169962524e2201ac7079c"), // tree HEAD:resource
		45: MustIDFromString("fb4bd4ec9220ed4fe0d9526d1b77147490ce8842"), // blob HEAD:run.sh
		46: MustIDFromString("c53e5f83ee07637b9383b412547d0b2f9e261f8d"), // tree HEAD:sameSHAs
		47: MustIDFromString("007cb92318c7bd3b56908ea8c2e54370245562f8"), // tree HEAD:src
		48: MustIDFromString("e0e63473c2593040d7d1c67637864821b28cef4b"), // blob HEAD:symlink.run.sh
		49: MustIDFromString("2ce918888b0fdd4736767360fc5e3e83daf47fce"), // blob HEAD:img/sourcegraph.png

		50: MustIDFromString("b39c8508bbc4b00ad2e24d358012ea123bcafd8d"), // tag v1.1.0

		51: MustIDFromString("1e24b564bf2298965d8037af42d3ae15ad7d225a"), // blob 755fd57:README.txt
		52: MustIDFromString("fbdcfef007c0c09061199e687087b18c3cf8e083"), // blob 755fd57:resources/labels.properties
		53: MustIDFromString("51680791956b43effdb2f16bccd2b4752d66078f"), // blob 755fd57:src/Main.groovy
		54: MustIDFromString("e69de29bb2d1d6434b8b29ae775ad8c2e48c5391"), // blob ef7bebf:fix.txt
	}
	submoduleSHA = MustIDFromString("6b08f76a5313fa3d26859515b30aa17a5faa2807")
)

const (
	repoPath             = "testdata/testrepo.git"
	testrepoObjectFormat = ObjectFormatSHA1
	testEmptyShaID       = EmptySha1ID
)

func initTestRepo() {
	ctx := context.Background()
	// Set up the test repository
	if !isExist(repoPath) {
		if err := Clone(ctx, "https://github.com/gogs/git-module-testrepo.git", repoPath, CloneOptions{
			Bare: true,
		}); err != nil {
			stdlog.Fatal(err)
		}
	}
	var err error
	testrepo, err = Open(repoPath)
	if err != nil {
		stdlog.Fatal(err)
	}
}
