//go:build test_sha256

package git

import (
	"bytes"
	"context"
	"fmt"
	stdlog "log"
	"os"
)

var (
	testrepoMarks = map[int64]Oid{
		// Commits, generated by `git rev-list --all | tac`
		1:  MustIDFromString("31a3d8bb18edda3252f7242035d4695ee9b8ddbd47d7c62f656756442c2e85af"),
		2:  MustIDFromString("a1a482f1f2fa00c70e892a0ecc49c0ef0295eb7f6bf96b51a7dd32e40c54e92e"),
		3:  MustIDFromString("8573f82fa6f1b1f3a74bd5df5a7e68db9477911cda33dc624cfd07cecccf6fe2"),
		4:  MustIDFromString("c41b25357f8e259ba78791a01a2dce80a677061d7474e7c35ff290d4527d9a49"),
		5:  MustIDFromString("5402a2cd6d628b46225e4fa5be0d854711472237d121ead1581fca4b3c8d0633"),
		6:  MustIDFromString("44f45f65f43901e58282d2861eb4661e1fa8f33ef156e0e340a599c306d73828"),
		7:  MustIDFromString("8e892031b84c4bf15314c3f7173549e0874442db76f429568f1fa55b49a1cfc0"),
		8:  MustIDFromString("a3e5aa80d28fae8260994aba69cb80ad442fdcb3b3971307b3383f92f81842a5"),
		9:  MustIDFromString("f812c295641e30395a5e02b05bbd18763335bd8867f5e7bdcf5510dbd6144b75"),
		10: MustIDFromString("a0e41bd21586bc939b7d7400c2066bb627fca7a2cbbe17a167ed03db1a9182bc"),
		11: MustIDFromString("206a8d713b97b4695e4f23e5660fd37b87d33c952965111e42f077cb44dbda93"),
		12: MustIDFromString("701cdc22435b22d31974188a4ba4a3f42746f57e7564761a98a65ff4de67f9b0"),
		13: MustIDFromString("8e32744b5ec628e9397d39fef23ed89b6465042945630e352028063307813725"),
		14: MustIDFromString("74f4d668782edc5276954505f6d2a954eda5b61dde2395d387e2a025ac070e88"),
		15: MustIDFromString("6a652d215eb60f2b319da986145810246a4fb4ff903cfc66710aeb66ae9c2a79"),
		16: MustIDFromString("772c8079c93111471b91b01ac22626677d1baefdc83c9646f1f482d149316edd"),
		17: MustIDFromString("74fec01c00c1863972cb13bfa3ed2acf8d46ded93fb97ac7290df68bd0198864"),
		18: MustIDFromString("d925b2b2d0778452a00c3d1d5b94a7cc3b2c540dc87219cfe5b292ea3877ed8f"),
		19: MustIDFromString("ff7369e546af022289c553b7c825c6934a4b6aa8d44d5d2408e8bba44725527b"),
		20: MustIDFromString("7a7e4c3508b5723d61b982e049655eca96350e1df1c5efe04a8caf6a50c0ecd0"),
		21: MustIDFromString("716c81cf2828bc20c3ae95ce73bbb978c503c400939800adf432efcea221b7cb"),
		22: MustIDFromString("1eb65ce7570a6249d955c477ccdcd1e8142d3e8696f2268a65c5aafafe2d7708"),
		23: MustIDFromString("629328565e5fa5ff0e5cd6e1d62d68f068cacfdca5a1cf6d957abbcc40e68c5f"),
		24: MustIDFromString("cda497d4c0d261045789f123ec274cd662384fb847e8f0a82fe93016546045a1"),
		25: MustIDFromString("de231aea47c5095ff5257fb9af8aebf260b48d07a1e84749cf3554a4e3ebd9a9"),
		26: MustIDFromString("489afb570dc4cc091f55bcbbea564171a54563b09272ec807b886916707d1f02"),
		27: MustIDFromString("3127f6e5e4e530dde76e8e3357ae37310c6c1fc2ab07194df2622c456160594c"),
		28: MustIDFromString("e814f101e4c215abaec1b2f42496c4012079c1f2d02519a8d389e8973e34c74a"),
		29: MustIDFromString("95a36dbd75ae6c85054678688660a5849c043d1c21b39cefbc1d6f87d93a5dd2"),
		30: MustIDFromString("d4043c6c6c5b313187a7ccfc0bc8f17dbe725374aa03a81bd6b49994e33f77bd"),
		31: MustIDFromString("e8983d273da9a8236d8566fdbf83a34499b2d5e89e5e60d8b3537d6cd1946026"),
		32: MustIDFromString("949e74b2fd94b95da3492e613656fc7fda5f7a6e82184ea291a89bd2b028dd2e"),

		34: MustIDFromString("6ee5b1e01c3084acd459c41a9aad860bda0a0a83b23e93fa3b8e67262acaed22"), // blob HEAD:.DS_Store
		35: MustIDFromString("4fe5cee2cdd0d2a7995f10ab9f7b2b09d061b62028a51653a61948adb4434dc8"), // blob HEAD:.gitattributes
		36: MustIDFromString("db1173e5dbc280c588ac18c12461db62cf09485299984c08c0b532b0d63ceab0"), // blob HEAD:.gitignore
		37: MustIDFromString("2523f972d932f186489bb4cd9746f65c72a34ff4210b80cd6c09c9865a08ad95"), // blob HEAD:.gitmodules
		38: MustIDFromString("4f015a6e9501b585b7823f588bae41ec901354bafe30a8fe9f82160099c5c584"), // blob HEAD:.travis.yml
		39: MustIDFromString("dd66873b93ef9e7f3909bb919f45bbd91540d85ea171043f21b4f0d830e404bb"), // blob HEAD:README.txt
		40: MustIDFromString("ef9d169adc6eda7180040708d8a888d2726f8429e08235a0a6f992c2737c1d17"), // blob HEAD:build.gradle
		41: MustIDFromString("ba2cc18e595b5f70a47cea3ed71f3568addd55e7bb5581a8918b7885abb7888e"), // tree HEAD:gogs
		42: MustIDFromString("ccfb232c491a6ba1cebce68dab2a9c3f4b79018ea45442dad99c281f52227807"), // tree HEAD:img
		43: MustIDFromString("a8e75d30f8ae30c37d91c14753f723b3b232e4293d9cc446c90c11570aee410e"), // blob HEAD:pom.xml
		44: MustIDFromString("a3291603bebc8a2b8d354e2fea44a3e093ff6b9f0171333a26ce8d56b8f6652c"), // tree HEAD:resource
		45: MustIDFromString("20f59dd73b24e3dc47f2bcf20d5d827095f1cea9778023e37b5d5d7cb36b9232"), // blob HEAD:run.sh
		46: MustIDFromString("5ea265eb087b456525021721cc2d33b005c998b5c8908b1d0122f118bb53bc9a"), // tree HEAD:sameSHAs
		47: MustIDFromString("e98f5bc0b76add753e2d330fb2974e596bdf8b96111237ebc204c4fe0280bc89"), // tree HEAD:src
		48: MustIDFromString("fdd5f856ccd57ffc0dc86a02c3d55863d078bb901c2b72353a20dc399f932536"), // blob HEAD:symlink.run.sh
		49: MustIDFromString("dae65197c87793004ef9f0bc2fac54aa4f74cf57e8bb11a274e06cce3d50fd50"), // blob HEAD:img/sourcegraph.png

		50: MustIDFromString("264607f7e6128c06d1bab93857dbaf10c1ad98cd98ade780a9adcfd388774056"), // tag v1.1.0

		51: MustIDFromString("6d86d830e90b4801ac5130275272cf9c047998a63a082d6afe3adead7527495a"), // blob 31a3d8b:README.txt
		52: MustIDFromString("93324ee06704d200656b2bc0ddd75c4262965a2ab2b7e151aece2cf692960678"), // blob 31a3d8b:resources/labels.properties
		53: MustIDFromString("a4de9b44e29e16ecb7fa9d1de3cc59216fdcde0fa36e193cf9e0e629e22d1815"), // blob 31a3d8b:src/Main.groovy
		54: MustIDFromString("473a0f4c3be8a93681a267e3b1e9a7dcda1185436fe141f7749120a303721813"), // blob 489afb5:fix.txt
	}
	submoduleSHA = MustIDFromString("8fa8e7ed491f06aa84c52730587547852f91e8d1b0b9105660209f253edd2c41")
)

const (
	repoPath             = "testdata/testrepo-sha256.git"
	testrepoObjectFormat = ObjectFormatSHA256
	testEmptyShaID       = EmptySha256ID
)

func initTestRepo() {
	ctx := context.Background()

	// Set up the test repository
	if !isExist(repoPath) {
		sha1RepoPath := tempPath()
		if err := Clone(ctx, "https://github.com/gogs/git-module-testrepo.git", sha1RepoPath, CloneOptions{
			Bare: true,
		}); err != nil {
			stdlog.Fatal(err)
		}
		defer os.RemoveAll(sha1RepoPath)
		sha1Repo, err := Open(sha1RepoPath)
		if err != nil {
			stdlog.Fatal(err)
		}
		err = Init(ctx, repoPath, InitOptions{Bare: true, ObjectFormat: "sha256"})
		if err != nil {
			stdlog.Fatal(err)
		}
		sha256Repo, err := Open(repoPath)
		if err != nil {
			stdlog.Fatal(err)
		}

		data, err := fastExport(ctx, sha1Repo)
		if err != nil {
			stdlog.Fatal(err)
		}
		err = fastImport(ctx, sha256Repo, data, map[string]map[string]string{
			"gogs/docs-api": {
				"6b08f76a5313fa3d26859515b30aa17a5faa2807": "8fa8e7ed491f06aa84c52730587547852f91e8d1b0b9105660209f253edd2c41",
			},
		})

		if err != nil {
			os.RemoveAll(repoPath)
			stdlog.Fatal(err)
		}
	}
	var err error
	testrepo, err = Open(repoPath)
	if err != nil {
		stdlog.Fatal(err)
	}
}

func fastExport(ctx context.Context, repo *Repository) ([]byte, error) {
	return exec(ctx, repo.path, []string{"fast-export", "--all"}, nil)
}

func fastImport(ctx context.Context, repo *Repository, data []byte, submoduleRewrite map[string]map[string]string) error {
	args := []string{"fast-import"}

	for submodule, hashes := range submoduleRewrite {
		frompath := tempPath()
		fromfile, err := os.Create(frompath)
		if err != nil {
			return err
		}
		defer os.Remove(frompath)
		topath := tempPath()
		tofile, err := os.Create(topath)
		if err != nil {
			fromfile.Close()
			return err
		}
		defer os.Remove(topath)

		markIndex := 0
		for from, to := range hashes {
			markIndex += 1
			fmt.Fprintf(fromfile, ":%d %s\n", markIndex, from)
			fmt.Fprintf(tofile, ":%d %s\n", markIndex, to)
		}
		fromfile.Close()
		tofile.Close()

		args = append(args,
			fmt.Sprintf("--rewrite-submodules-from=%s:%s", submodule, frompath),
			fmt.Sprintf("--rewrite-submodules-to=%s:%s", submodule, topath))
	}

	c, cancel := cmd(ctx, repo.path, args, nil)
	defer cancel()
	c.Input(bytes.NewReader(data))
	return c.Run().Wait()
}
